services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/lib/sqlserver/data
    ports:
      - "1435:1433"
  
  redis:
    image: "redis:alpine"
    container_name: redisdb
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - redis_data:/data

#network section
networks:
  default:
    name: ecommerce
    driver: bridge

#volumes section
volumes:
  sqlserver_data:
    name: sqlserver_data
  redis_data:
    name: redis_data  

